name: Windows

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Environment variables
      run: |
        dir env:

    - name: Path
      run: |
        echo $env:Path

    - name: Root directory
      run: |
        dir C:\
