name: Windows

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Environment variables
      run: |
        dir env:

    - name: Path
      run: |
        ForEach ($dir in $env:Path.Split(';')) {
          echo $dir
        }

    - name: Root directory
      run: |
        dir C:\

    - name: C:\ProgramData
      run: |
        dir C:\ProgramData
